shaders/urls.py
# -*- coding: UTF-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url

from . import views

app_name = "shaders"
urlpatterns = [
    url(r'^/?$',                                views.shader_list_view,         name='shader_list'),
    url(r'^edit/(?P<sid>[A-Z0-9]+)/?$',         views.shader_edit_view,         name='shader_edit'),
    url(r'^fork/(?P<sid>[A-Z0-9]+)/?$',         views.shader_fork_view,         name='shader_fork'),
    url(r'^newsourceid/(?P<sid>[A-Z0-9]+)/?$',  views.shader_new_source_id,     name='shader_new_source_id'),

    url(r'^find_include/?$',                    views.shader_find_include,      name='shader_find_include'),

    url(r'^load/(?P<sid>[A-Z0-9]+)/?$',         views.shader_load_json,         name='shader_load'),
    url(r'^save/(?P<sid>[A-Z0-9]+)/?$',         views.shader_save_json,         name='shader_save'),
]

shadertox/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',  include("shaders.urls")),
]

shaders/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import random

from django.utils import timezone
from django.db import models, OperationalError
from django.utils.translation import ugettext_lazy as _
from django.urls import reverse
from django.db import transaction


def get_new_model_id(Model, field_name):
    possible = [chr(c) for c in range(ord('A'), ord('Z')+1)]
    possible += [chr(c) for c in range(ord('0'), ord('9')+1)]
    while True:
        shader_id = "".join(possible[random.randrange(len(possible))]
                            for i in range(10))
        try:
            Model.objects.get(**{field_name: shader_id})
        except (Model.DoesNotExist, OperationalError):
            return shader_id


def get_new_shader_id():
    return get_new_model_id(Shader, "shader_id")


def get_new_stage_id():
    return get_new_model_id(ShaderStage, "stage_id")


def get_new_source_id():
    return get_new_model_id(ShaderSource, "source_id")


class Shader(models.Model):

    shader_id = models.CharField(verbose_name=_("shader id"), max_length=10, default=get_new_shader_id)
    name = models.CharField(verbose_name=_("name"), max_length=100)
    description = models.TextField(verbose_name=_("description"), default="")

    forked_from = models.ForeignKey(verbose_name=_("forked from"), to="Shader", on_delete=models.PROTECT,
                                    null=True)


class ShaderStage(models.Model):

    stage_id = models.CharField(verbose_name=_("stage id"), max_length=10, default=get_new_stage_id)

    shader = models.ForeignKey(verbose_name=_("shader"), to="Shader", on_delete=models.PROTECT)
    name = models.CharField(verbose_name=_("name"), max_length=100)
    index = models.IntegerField(verbose_name=_("index"), default=0)

    stage_type = models.CharField(verbose_name=_("type"), max_length=20, default="main",
                                  choices=(
        ("main", _("main")),
        ("buffer", _("buffer")),
    ))


class ShaderSource(models.Model):

    source_id = models.CharField(verbose_name=_("shader id"), max_length=10, default=get_new_source_id)
    stage = models.ForeignKey(verbose_name=_("shader stage"), to="ShaderStage", on_delete=models.PROTECT)
    source_type = models.CharField(verbose_name=_("type"), max_length=20, default="include",
                                   choices=(
        ("vertex", _("vertex")),
        ("fragment", _("fragment")),
        ("include", _("include")),
    ))
    name = models.CharField(verbose_name=_("name"), max_length=100)
    source = models.TextField(verbose_name=_("source"))


class ShaderView(models.Model):
    shader = models.ForeignKey(verbose_name=_("shader"), to="Shader", on_delete=models.PROTECT)
    date = models.DateTimeField(verbose_name=_("date"), default=timezone.now)
    session_key = models.CharField(verbose_name=_("session key"), max_length=40, default="")

shaders/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import json

from django.shortcuts import render
from django.http import JsonResponse, Http404, HttpResponseRedirect
from django.urls import reverse
from django.db import transaction
from django.utils.translation import ugettext_lazy as _

from .tools import *


def shader_list_view(request):
    ctx = {
        "shaders": Shader.objects.all(),
    }
    return render(request, "shaders/shader-list.html", ctx)


def shader_edit_view(request, sid):
    try:
        shader = Shader.objects.get(shader_id=sid)
    except (Shader.DoesNotExist, ValueError):
        raise Http404

    fork_ids = [t[0] for t in Shader.objects.filter(forked_from=shader).values_list("shader_id")]
    ctx = {
        "shader": shader,
        "can_edit": True,
        "fork_ids": fork_ids,
        "num_forks": len(fork_ids),
        "num_views": ShaderView.objects.filter(shader=shader).count(),
    }


    if not request.session.session_key:
        request.session.create()
    ShaderView.objects.get_or_create(shader=shader, session_key=request.session.session_key)

    return render(request, "shaders/shader-edit.html", ctx)


def shader_load_json(request, sid):
    try:
        shader = Shader.objects.get(shader_id=sid)
    except (ValueError, Shader.DoesNotExist):
        return JsonResponse({"error": "Unknown id"})

    return JsonResponse(
        shader_to_json(shader)
    )


def shader_save_json(request, sid):
    try:
        shader = Shader.objects.get(shader_id=sid)
    except (ValueError, Shader.DoesNotExist):
        return JsonResponse({"error": "Unknown id"})

    if not request.is_ajax():
        return JsonResponse({"error": "no ajax data"})
    try:
        data = json.load(request)
    except BaseException as e:
        return JsonResponse({"error": "Could not load json: %s" % e})

    try:
        json_to_shader(data, shader)
    except DeserializationError as e:
        return JsonResponse({"error": "Could not store shader: %s" % e})

    return JsonResponse({"message": _("Shader %s saved") % shader.shader_id})


def shader_fork_view(request, sid):
    try:
        shader = Shader.objects.get(shader_id=sid)
    except (Shader.DoesNotExist, ValueError):
        raise Http404

    new_shader = fork_shader(shader)

    return HttpResponseRedirect(reverse("shaders:shader_edit", args=(new_shader.shader_id,)))


def shader_new_source_id(request, sid):
    #try:
    #    shader = Shader.objects.get(shader_id=sid)
    #except (Shader.DoesNotExist, ValueError):
    #    raise Http404
    return JsonResponse({"id": get_new_source_id()})


def shader_find_include(request):
    shader_name = request.GET.get("shader", "")
    source_name = request.GET.get("name", "")
    if not shader_name or not source_name:
        return JsonResponse({"error": _("invalid params")})

    try:
        shader = Shader.objects.get(shader_id=shader_name)
    except Shader.DoesNotExist:
        try:
            shader = Shader.objects.get(name=shader_name)
        except Shader.DoesNotExist:
            return JsonResponse({"error": _("Shader '%s' not found") % shader_name})

    try:
        source = ShaderSource.objects.get(stage__shader=shader, name=source_name)
    except ShaderSource.DoesNotExist:
        return JsonResponse({"error": _("Source '%s' not found in shader '%s'") % (source_name, shader_name)})

    ret = source_to_json(source)
    ret["readonly"] = True
    ret["name"] = "%s/%s" % (shader_name, source_name)
    return JsonResponse({"source": ret})

shaders/templates/shaders/base.html
{% load static %}
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-US">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    {% if title %}<title>{{ title ]}</title>{% endif %}
    <meta name="KEYWORDS" content="shader webgl" />
    <meta name="DESCRIPTION" content="Shadertox - an online shader editor" />
    <meta name="author" content="Stefan Berke" />

    <link rel="stylesheet" type="text/css" href="{% static 'shaders/cm/codemirror.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'shaders/cm/codemirror_theme.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'shaders/style.css' %}" />

    <script type="text/javascript" src="{% static 'shaders/jquery-3.1.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'shaders/js.cookie.js' %}"></script>
    <script type="text/javascript" src="{% static 'shaders/cm/codemirror.js' %}"></script>
    <script type="text/javascript" src="{% static 'shaders/cm/codemirror_glsl.js' %}"></script>
    <script type="text/javascript" src="{% static 'shaders/webgl.js' %}"></script>
    <script type="text/javascript" src="{% static 'shaders/editor.js' %}"></script>
    <script type="text/javascript" src="{% static 'shaders/tools.js' %}"></script>

</head>

<body>
    <div id="main-container">
        {% block content %}
            <h1>CONTENT</h1>
        {% endblock %}
        <pre id="debug"></pre>
    </div>
</body>

</html>

shaders/templates/shaders/parts/code-editor.html
<div id="code-editor-container">

    <div id="code-editor-tab-header"></div>

    <div id="code-editor-header"></div>

    <div id="code-editor">
        <textarea id="code-mirror"></textarea>
    </div>

    <div id="code-editor-tools">
        <div class="button" id="compile-button" title="Alt-Enter">COMPILE</div>
        <div class="button" id="save-button" title="Ctrl-S">SAVE</div>
    </div>

    <div id="code-editor-log"></div>
</div>

shaders/templates/shaders/parts/shader-canvas.html
<canvas width="320" height="200" id="canvas-{{ shader.shader_id }}"></canvas>

shaders/templates/shaders/parts/shader-window.html
{% load i18n %}

<div class="shader-container">

    {% include './shader-canvas.html' %}
    <div>
        <div class="button" id="play-button"></div>
        <div class="render-number"><span id="play-time"></span><span class="small-font">s</span></div>
        <div class="render-number"><span id="frames-per-second"></span><span class="small-font">fps</span></div>
    </div>

    <div class="shader-name">
        "<span id="shader-name" {% if can_edit %}contenteditable="true"{% endif %}>{{ shader.name }}</span>"
    </div>

    <div class="shader-fork-line">
        <form class="inline" method="POST" action="{% url 'shaders:shader_fork' shader.shader_id %}">
            <input type="submit" class="button inline" value="{% trans 'fork' %}">
            {% csrf_token %}
        </form>

        {% if shader.forked_from %}
            <span class="small-font inline">
            {% trans 'forked from' %}
                "<a href="{% url 'shaders:shader_edit' shader.forked_from.shader_id %}">{{ shader.forked_from.name }}</a>"
            </span>
        {% endif %}

        <span class="small-font inline">
            {% if num_forks == 0 %}
            {% elif num_forks == 1 %}
                | <a href="{% url 'shaders:shader_edit' fork_ids.0 %}">{% trans 'one fork' %}</a>
            {% else %}
                | {{ num_forks }} {% trans 'forks' %}
            {% endif %}
        </span>

        <span class="small-font inline">
            | {{ num_views }} {% trans 'views' %}
        </span>
    </div>

    <div id="shader-description" contenteditable="true">{{ shader.description|safe }}</div>
</div>

shaders/templates/shaders/shader-edit.html
{% extends 'shaders/base.html' %}
{% load static i18n %}

{% block content %}

<p><a class="button" href="{% url 'shaders:shader_list' %}">all</a></p>

<table>
    <tr>
        <td valign="top">
            {% include './parts/shader-window.html' %}
        </td>

        <td valign="top">
            {% include './parts/code-editor.html' %}
        </td>
    </tr>
</table>

<script>
    var ctx, editor;

    $(function() {

        $.ajax("{% url 'shaders:shader_load' shader.shader_id %}").done(function(data) {
            if (data.error) {
                alert(data.error);
                return;
            }

            ctx = getGlContext("#canvas-" + data.id);
            ctx.loadTexture(0, "{% static 'shaders/img/bob.png' %}", true);
            editor = getEditorFromJson(data, ctx);
            editor.compile();
        });

        // RENDER WINDOW HOOKS
        $('#play-button').on("click", function() {
            ctx.togglePlaying();
        });

        // SHADER INFO EDIT HOOKS

        // Ricardo Azzi Silva: https://stackoverflow.com/questions/32522953/remove-focus-from-a-content-editable-div
        $(document).on('mousedown', '[contenteditable]', function(e){
            $(this).attr('contenteditable', true);
            $(this).focus();
        });
        $(document).on('blur', '[contenteditable]', function(e){
            $(this).attr('contenteditable', false);
        });

        $('#shader-name').on("keydown", function(e) {
            if (e.originalEvent.code == "Enter") {
                e.preventDefault();
                $(e).attr('contenteditable', false);
                window.getSelection().removeAllRanges();
            }
        });

        // GLOBAL KEYS
        $("body").on("keydown", function(e) {

            var key = undefined;
            // Alan Bellows: https://stackoverflow.com/questions/93695/best-cross-browser-method-to-capture-ctrls-with-jquery
            var possible = [ e.key, e.keyIdentifier, e.keyCode, e.which ];
            while (key === undefined && possible.length > 0)
                key = possible.pop();
            //console.log(key);
            if (!key)
                return;

            if ((key == '115' || key == '83' ) && (e.ctrlKey || e.metaKey) && !(e.altKey)) {
                e.preventDefault();
                editor.save();
            }
            if (key == '13' && e.altKey) {
                e.preventDefault();
                editor.compile();
            }

        });
    });
</script>

{% endblock %}

shaders/templates/shaders/shader-list.html
{% extends 'shaders/base.html' %}


{% block content %}

<ul>
{% for shader in shaders %}
    <li><a href="{% url 'shaders:shader_edit' shader.shader_id %}">{{ shader.name }}</a></li>
{% endfor %}
</ul>

{% endblock %}